# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97537e9d78740623403d98e592405c02af4da150ec3591ef21b15555b475d99a2f590e5548d648bc2643d5435d51025774ece7b2350b8c407ea42cc9a69af091
  # twitter_api_key: XvldEmYHhB1oH3evAas7qZxSH
  # twitter_api_secret: aRL0Jpz2e0b03abAKbu9S6GYbmpY8WBBt0toHt0eBMVhAi4voS

test:
  secret_key_base: f30d55bcd6b225efd9dbdee3f26ec3bdf234f58c1553953fdf1b90e1180c0ee675361172ce2591d93a71d740fb195c924dfc664c15d586836348a7c70fc89542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
